export const DUPLICATE_CODE_SMELL_HINT_TYPE = "duplicate_code";
export const SHAREABLE_CODE_HINT_TYPE = "SHAREABLE_CODE_HINT_TYPE";
export const RENAMABLE_CUSTOM_BLOCK = "RENAMABLE_CUSTOM_BLOCK";
export const DUPLICATE_CONSTANT_HINT_TYPE = "duplicate_constant";
export const BROAD_SCOPE_VAR_HINT_TYPE = "broad_scope_var";

export const CONTEXT_MENU_REFACTOR = "CONTEXT_MENU_REFACTOR";
export const CONTEXT_MENU_INFO = "CONTEXT_MENU_INFO";
export const CONTEXT_MENU_CODE_SHARE = "CONTEXT_MENU_CODE_SHARE";
export const CONTEXT_MENU_RENAME_BLOCK = "CONTEXT_MENU_RENAME_BLOCK";